### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by rubenrouwhof** [MinBZK/amt#100]
## Description
Depends: https://github.com/orgs/MinBZK/projects/7/views/9?pane=issue&itemId=73000793
The goal of this task is to implement a functional and intuitive navigation bar for the AMT. This navigation bar should enhance the user experience by providing easy access to the main sections of the application.

The navigation consists out of three parts to always clearly communication where the user is.

1. **Main navigation** Shows main pages such as home, projects
2. **Sub navigation** Shows different pages within a project
3. **Breadcrumbs** Provides a trail for the user to follow back to main/sub pages

## Acceptance Criteria

1. Navigation bar is visible on all pages.
2. Main navigation bar includes links to the following sections:
    - Logo/icon that directs to home
    - Projects
    - Language
3. Breadcrumb includes projects/new project
4. Sub navigation includes links to 
    - Project board
    - System card
5. It should be possible to add items to both bars
6. Main navigation bar fixes on top of screen on scroll down
7. Responsive design for mobile devices. -> Just rescale (if stuff will break after scaling then we make new tickets from this)
8. Clear visual feedback when selecting menu items.
9. Breakpoint at 768px

![Image](https://github.com/user-attachments/assets/bae1085c-5e7c-43c4-8d3e-6b7a38252703)

## Discovery
https://app.clickup.com/9015737202/v/dc/8cp2evj-1815/8cp2evj-1815

## Concept designs

![Image](https://github.com/user-attachments/assets/fd5720f1-78ff-4d52-8721-676df7508b2c)

![Image](https://github.com/user-attachments/assets/11a03e15-1000-4955-a200-95d7cf1a5665)

![Image](https://github.com/user-attachments/assets/85ab15e8-3003-4bbc-b05b-6117a71b3e71)
![Image](https://github.com/user-attachments/assets/3f088cc6-f20c-40d2-bfb9-dc89632d0bc3)

Make use of the components ROOS from RVO has? https://nl-design-system.github.io/rvo/docs/

**Comment by robbertbos** [comment]
@rubenrouwhof what do you think:
1. of removing acceptance criteria 5? In the current designs, the logo is shown on top, but for me, this is not a requirement. For me, it's okay to remove it from the acceptance criteria.
2. about that if a page has a sub-navigation that we fix on the sub-navigation, i.e., the main navigation bar?

**Comment by rubenrouwhof** [comment]
1. Yes agree
2. I think it helps to see main navigation as well for users to exactly now where they are and navigate to other pages. Now with only two pages we could do it, but i think when we have more this can potentially be problematic.

**Comment by rubenrouwhof** [comment]
I have email the rijkshuisstijl coordinator regarding logo, font and icon usage.
