### ISSUE TITLE
⏲ -8 Research: create users

### ISSUE THREAD

**Issue by anneschuth** [MinBZK/amt#150]
Currently, we don't have users in the AMT. 

We will use an external system that provides users.

Do we also need our own user table? 

## Implementation notes

if we use an external system, we have 2 options: 
- single-sign on: SAML / openID connect (probably we will use SAML) 
      - Self hosting
      - Use ext service   
- shared: OAuth2 (Github uses this) 

- What do we use at the Dutch Government 
    - Anne checks with Eelco which identify providers are used 
    - What does JenV use?
- We will use Keycloak: https://www.keycloak.org
- Research: what if an organization does not want to use our Keycloak and wants to self-host AMT?

**Comment by uittenbroekrobbert** [comment]
@berrydenhartog @anneschuth @robbertbos @rubenrouwhof 
This ticket now focuses on authentication mostly so a user can access AMT. What I miss, but maybe that's a different story, is how authorisation will work. In the context of:
- who can create new projects?
- how is access to the projects managed, is this externally provided, by 'role' f.e., and if so, does that mean a user always has the same role for any project, or is a role per project and if so, how do we manage that?

Is that something for this ticket, or is that for later concern?

**Comment by uittenbroekrobbert** [comment]
Correction, the research document @berrydenhartog wrote does include a part about authorization. I still do wonder about my questions though, mostly the 'role per project, or always the same role for all projects'.
