### ISSUE TITLE
Fill in questionnaire task

### ISSUE THREAD

**Issue by anneschuth** [MinBZK/amt#154]
Currently, we can only view or drag a task, but there is no option to do anything with it (for example, answer an assessment question). 

- We want a task to be clickable
- For each task, a URL needs to be created and navigated to, f.e. /tasks/{id}
- When you click on a task, the details for that task are shown (including the form to answer the question)
- Answers to a task need to be saved in the database

See the instrument registry for task types.

**Comment by robbertbos** [comment]
We have a solution in the most recent plans that makes this ticket absolute.
