### ISSUE TITLE
Project home page (section with info about project)

### ISSUE THREAD

**Issue by anneschuth** [MinBZK/amt#184]
https://www.figma.com/design/AvpyJlrHjnc490HgyY7LTw/Project-overview?node-id=2058-1038&t=GhthuiT4Rgrdpa6O-4

![Image](https://github.com/user-attachments/assets/19f5f07f-520a-4d81-acf6-ebac89631721)
![Image](https://github.com/user-attachments/assets/b42bfe3f-c65c-4ddd-a96f-3671e27e8211)
![Image](https://github.com/user-attachments/assets/e659b393-6913-429d-bf58-6fba5bc4cc41)
![Image](https://github.com/user-attachments/assets/16c9e031-a957-4e6e-b3ef-1e2d12f29b4d)

Notes:
- This view replaces the current home view (tasks), tasks are moved to a tab
- This new view also replaces the system card viewer (or, it breaks it up in tabs)
- The status (color) for the top left panel can be mocked for now.
- The status (color) for the the top right panel can be computed based instrument-state-checker (cli) that we already implemented.
- Out of scope for now: downloading system card

Technical notes:
- we see this mostly as refactoring the system card viewer
- break up the check_state.py cli function and lift the business logic elsewhere.

**Comment by robbertbos** [comment]
Search functionality and gravatars are out of scope for this ticket
