### ISSUE TITLE
Make a proposal on how to export the metadata for the AMT

### ISSUE THREAD

**Issue by anneschuth** [MinBZK/amt#186]
## Context

With the AMT tool we will also generate metadata like the status of the tasks before they have been moved to done or the discussions on a task which will not be exported to a System Card. We should think about how we want to export this metadata and potentially also read this in another tool or another instance of the AMT tool potentially locally.

## Deliverable

Proposal in which format to export the metadata
Potentially already code this import and export functionality into the AMT tool

**Comment by robbertbos** [comment]
In the most recent plans, we store this kind of metadata in the system card, which makes this ticket redundant.
