### ISSUE TITLE
Remove (system card) mocks

### ISSUE THREAD

**Issue by anneschuth** [MinBZK/amt#298]
- [x] We remove all mocking from the AMT and move everything related to system_cards to the Project.system_card (serialized to the db)
  - [x] Static System card from disk, for instance here: [/amt/api/routes/project.py#L304](https://github.com/MinBZK/amt/blob/dba3cf7a90d9cfc44087f65b0cf9bcf7f856276a/amt/api/routes/project.py#L304)
  - [x] Fixed AI Act profile in project creation [/amt/api/routes/projects.py#L125](https://github.com/MinBZK/amt/blob/dba3cf7a90d9cfc44087f65b0cf9bcf7f856276a/amt/api/routes/projects.py#L125)
- [x] out of scope:
  - [x] #309
  - [x] Obtaining correct requirements/measures based on AI Act Profile
- [x] We keep the file system storage abstractions around
- [ ] We _may_ want to keep only the option to mock (through selecting a default template) when creating a project? 
- [ ] out of scope is increasing the test coverage: #312

**Comment by uittenbroekrobbert** [comment]
For implementation of using the template when creating a new project; A hidden field is used instead of the option to select a template, as the latter would make things more complicated at this point. This is by request of @robbertbos
