### ISSUE TITLE
Set proper caching TTL on static files

### ISSUE THREAD

**Issue by anneschuth** [MinBZK/amt#86]
We serve static files which are cached. We want to have control over how files are cached.

We can use cache headers, like e-tag, cache-control to specify how browsers can cache the files.

## Technical steps
* Research what caching strategy we would want to use, and choose per file type what caching is most valid, note we also generate dynamic pages which never should be cached
* Implement the caching strategy

## Implementation notes
* for static resources we use directly, we can use immutable caching (the url will include the etag then)
* for derived static resources (like fonts used within a css file), we will use "1 hour revalidate" caching; we can assume but should not rely on those resources never changing (and revalidate means a head request is done after the caching timeout has expired)
* fastapi already sends etag and last-modified tags, we add custom cache-control headers
* Dynamic pages generated from Jinja templates always have a 'no-cache no-store' strategy

**Comment by robbertbos** [comment]
For updating static files, such as CSS, adding something like the MD5 hash to the file name could be handy. In Django they call it [ManifestStaticFilesStorage](https://docs.djangoproject.com/en/5.0/ref/contrib/staticfiles/#manifeststaticfilesstorage). Maybe someone has build something similar for FastAPI.

@anneschuth FYI
